### ISSUE TITLE
No Module Named Modules

### ISSUE THREAD

**Issue by Artaiios** [SpiderLabs/social_mapper#15]
Trackback (most recent call last):
   File "social_mapper.py", line 1, in <module>
      from modules import fecebookfinder
ImportError: No module named modules

**Comment by Ewpratten** [comment]
This is fixed in my pending pr. https://github.com/SpiderLabs/social_mapper/pull/8

**Comment by torerobo** [comment]
Sorry, but I have the same error.
№ 2 I did not understand what needs to be done (what steps need to be done)
I'm writing in the terminal "import facebookfinder.py", but the screen starts to take screenshots and that's it. Write (please correct) please Readme how to start the software correctly

from modules import facebookfinder
ImportError: No module named modules

**Comment by torerobo** [comment]
@Krafty-Coder Meanwhile, I'm no stranger to python.
The software does not start, you need the exact command in the terminal: how to run the software without errors (what you need to do with the modules the exact command is needed!).

In addition, the problem is exacerbated by the language barrier (en)

**Comment by Krafty-Coder** [comment]
My bad @torerobo Guess I didn't understand the error at hand

**Comment by torerobo** [comment]
> You can just create an empty file in /modules called init.py
I created an empty file modules called init.py (However, I still get an error)

python social_mapper.py -f imagefolder -i /home/social_mapper/fff -m fast -fb -tw
Traceback (most recent call last):
  File "social_mapper.py", line 1, in <module>
    from modules import facebookfinder
ImportError: No module named modules

**Comment by Ewpratten** [comment]
@torerobo take a look at pr: https://github.com/SpiderLabs/social_mapper/pull/8
