### ISSUE TITLE
no module named facebook please help

### ISSUE THREAD

**Issue by The-Real-StormDog** [SpiderLabs/social_mapper#24]
python social_mapper.py -f imagefolder -i /root/Pictures -m fast -fb -tw
Traceback (most recent call last):
  File "social_mapper.py", line 12, in <module>
    import facebook
ImportError: No module named facebook

**Comment by Greenaxio** [comment]
look at previous Issues!!!
`pip install facebook-sdk`

[#3](https://github.com/SpiderLabs/social_mapper/issues/3)

**Comment by Ewpratten** [comment]
fixed in pr: https://github.com/SpiderLabs/social_mapper/pull/8

**Comment by asarra** [comment]
@Ewpratten so this is how we meet each other. I'm Angry Client from DR.
Was searching the same issue on google lol

**Comment by Ewpratten** [comment]
> @Ewpratten so this is how we meet each other. I'm Angry Client from DR.
> Was searching the same issue on google lol

Hello!

It's funny how many people i meet from DR on other sites. Plus the fact that people just recognize my name in general.

**Comment by asarra** [comment]
> 
> 
> > @Ewpratten so this is how we meet each other. I'm Angry Client from DR.
> > Was searching the same issue on google lol
> 
> Hello!
> 
> It's funny how many people i meet from DR on other sites. Plus the fact that people just recognize my name in general.

Hey!

Exactly! DR is like this underground location where everyone wears a mask to cover the identity, but outside of DR some still have the same mask they wore on DR 😆

**Comment by founa96** [comment]
am new here, so how was this issue resolved? am having the same problem
