### ISSUE TITLE
No module named Selenium

### ISSUE THREAD

**Issue by Greenaxio** [SpiderLabs/social_mapper#6]
`pip install selenium ` is saying that it's installed

```
Traceback (most recent call last):
  File "social_mapper.py", line 3, in <module>
    import facebookfinder
  File "./modules\facebookfinder.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium
```

**Comment by Ewpratten** [comment]
i get this too.

**Comment by Ewpratten** [comment]
fixed with `python -m pip install selenium`

**Comment by Ewpratten** [comment]
you could also try `pip install -r --no-cache-dir --upgrade requirements.txt`

It will force pip to redownload (the correct version) the module from the servers.

**Comment by Greenaxio** [comment]
Worked when running the command from above with the correct python version

**Comment by derilous** [comment]
ran all these commands, still facing the issue. on running `pip install -r --no-cache-dir --upgrade requirements.txt` , I got **Could not open requirements file: [ERRNO 2] No such file or deirectory**.

**Comment by derilous** [comment]
**--no-cache-dir** to complete the error message

**Comment by Ewpratten** [comment]
sounds like you are in the wrong directory (hence not being able to find the requirements file)

**Comment by Ewpratten** [comment]
oh. wait. It looks like the directory changed. Try: 

```sh
pip install -r --no-cache-dir --upgrade setup/requirements.txt
```

**Comment by jordanleo-27** [comment]
I have tried and i cant get it to work

**Comment by jdiegochg10** [comment]
i wordked for me: `python -m pip install selenium`
